default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: demo_development

test:
  <<: *default
  database: demo_test

production:
  <<: *default
  database: demo